# coding=utf-8

import re
from collections import namedtuple

wgl4_doc = """
# see <https://www.microsoft.com/typography/otspec/WGL4.htm>.
0020 #   SPACE
0021 # ! EXCLAMATION MARK
0022 # " QUOTATION MARK
0023 # # NUMBER SIGN
0024 # $ DOLLAR SIGN
0025 # % PERCENT SIGN
0026 # & AMPERSAND
0027 # ' APOSTROPHE
0028 # ( LEFT PARENTHESIS
0029 # ) RIGHT PARENTHESIS
002A # * ASTERISK
002B # + PLUS SIGN
002C # , COMMA
002D # - HYPHEN-MINUS
002E # . FULL STOP
002F # / SOLIDUS
0030 # 0 DIGIT ZERO
0031 # 1 DIGIT ONE
0032 # 2 DIGIT TWO
0033 # 3 DIGIT THREE
0034 # 4 DIGIT FOUR
0035 # 5 DIGIT FIVE
0036 # 6 DIGIT SIX
0037 # 7 DIGIT SEVEN
0038 # 8 DIGIT EIGHT
0039 # 9 DIGIT NINE
003A # : COLON
003B # ; SEMICOLON
003C # < LESS-THAN SIGN
003D # = EQUALS SIGN
003E # > GREATER-THAN SIGN
003F # ? QUESTION MARK
0040 # @ COMMERCIAL AT
0041 # A LATIN CAPITAL LETTER A
0042 # B LATIN CAPITAL LETTER B
0043 # C LATIN CAPITAL LETTER C
0044 # D LATIN CAPITAL LETTER D
0045 # E LATIN CAPITAL LETTER E
0046 # F LATIN CAPITAL LETTER F
0047 # G LATIN CAPITAL LETTER G
0048 # H LATIN CAPITAL LETTER H
0049 # I LATIN CAPITAL LETTER I
004A # J LATIN CAPITAL LETTER J
004B # K LATIN CAPITAL LETTER K
004C # L LATIN CAPITAL LETTER L
004D # M LATIN CAPITAL LETTER M
004E # N LATIN CAPITAL LETTER N
004F # O LATIN CAPITAL LETTER O
0050 # P LATIN CAPITAL LETTER P
0051 # Q LATIN CAPITAL LETTER Q
0052 # R LATIN CAPITAL LETTER R
0053 # S LATIN CAPITAL LETTER S
0054 # T LATIN CAPITAL LETTER T
0055 # U LATIN CAPITAL LETTER U
0056 # V LATIN CAPITAL LETTER V
0057 # W LATIN CAPITAL LETTER W
0058 # X LATIN CAPITAL LETTER X
0059 # Y LATIN CAPITAL LETTER Y
005A # Z LATIN CAPITAL LETTER Z
005B # [ LEFT SQUARE BRACKET
005C # \ REVERSE SOLIDUS
005D # ] RIGHT SQUARE BRACKET
005E # ^ CIRCUMFLEX ACCENT
005F # _ LOW LINE
0060 # ` GRAVE ACCENT
0061 # a LATIN SMALL LETTER A
0062 # b LATIN SMALL LETTER B
0063 # c LATIN SMALL LETTER C
0064 # d LATIN SMALL LETTER D
0065 # e LATIN SMALL LETTER E
0066 # f LATIN SMALL LETTER F
0067 # g LATIN SMALL LETTER G
0068 # h LATIN SMALL LETTER H
0069 # i LATIN SMALL LETTER I
006A # j LATIN SMALL LETTER J
006B # k LATIN SMALL LETTER K
006C # l LATIN SMALL LETTER L
006D # m LATIN SMALL LETTER M
006E # n LATIN SMALL LETTER N
006F # o LATIN SMALL LETTER O
0070 # p LATIN SMALL LETTER P
0071 # q LATIN SMALL LETTER Q
0072 # r LATIN SMALL LETTER R
0073 # s LATIN SMALL LETTER S
0074 # t LATIN SMALL LETTER T
0075 # u LATIN SMALL LETTER U
0076 # v LATIN SMALL LETTER V
0077 # w LATIN SMALL LETTER W
0078 # x LATIN SMALL LETTER X
0079 # y LATIN SMALL LETTER Y
007A # z LATIN SMALL LETTER Z
007B # { LEFT CURLY BRACKET
007C # | VERTICAL LINE
007D # } RIGHT CURLY BRACKET
007E # ~ TILDE
00A0 #   NO-BREAK SPACE
00A1 # ¡ INVERTED EXCLAMATION MARK
00A2 # ¢ CENT SIGN
00A3 # £ POUND SIGN
00A4 # ¤ CURRENCY SIGN
00A5 # ¥ YEN SIGN
00A6 # ¦ BROKEN BAR
00A7 # § SECTION SIGN
00A8 # ¨ DIAERESIS
00A9 # © COPYRIGHT SIGN
00AA # ª FEMININE ORDINAL INDICATOR
00AB # « LEFT-POINTING DOUBLE ANGLE QUOTATION MARK
00AC # ¬ NOT SIGN
00AD # ­ SOFT HYPHEN
00AE # ® REGISTERED SIGN
00AF # ¯ MACRON
00B0 # ° DEGREE SIGN
00B1 # ± PLUS-MINUS SIGN
00B2 # ² SUPERSCRIPT TWO
00B3 # ³ SUPERSCRIPT THREE
00B4 # ´ ACUTE ACCENT
00B5 # µ MICRO SIGN
00B6 # ¶ PILCROW SIGN
00B7 # · MIDDLE DOT
00B8 # ¸ CEDILLA
00B9 # ¹ SUPERSCRIPT ONE
00BA # º MASCULINE ORDINAL INDICATOR
00BB # » RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK
00BC # ¼ VULGAR FRACTION ONE QUARTER
00BD # ½ VULGAR FRACTION ONE HALF
00BE # ¾ VULGAR FRACTION THREE QUARTERS
00BF # ¿ INVERTED QUESTION MARK
00C0 # À LATIN CAPITAL LETTER A WITH GRAVE
00C1 # Á LATIN CAPITAL LETTER A WITH ACUTE
00C2 # Â LATIN CAPITAL LETTER A WITH CIRCUMFLEX
00C3 # Ã LATIN CAPITAL LETTER A WITH TILDE
00C4 # Ä LATIN CAPITAL LETTER A WITH DIAERESIS
00C5 # Å LATIN CAPITAL LETTER A WITH RING ABOVE
00C6 # Æ LATIN CAPITAL LETTER AE
00C7 # Ç LATIN CAPITAL LETTER C WITH CEDILLA
00C8 # È LATIN CAPITAL LETTER E WITH GRAVE
00C9 # É LATIN CAPITAL LETTER E WITH ACUTE
00CA # Ê LATIN CAPITAL LETTER E WITH CIRCUMFLEX
00CB # Ë LATIN CAPITAL LETTER E WITH DIAERESIS
00CC # Ì LATIN CAPITAL LETTER I WITH GRAVE
00CD # Í LATIN CAPITAL LETTER I WITH ACUTE
00CE # Î LATIN CAPITAL LETTER I WITH CIRCUMFLEX
00CF # Ï LATIN CAPITAL LETTER I WITH DIAERESIS
00D0 # Ð LATIN CAPITAL LETTER ETH
00D1 # Ñ LATIN CAPITAL LETTER N WITH TILDE
00D2 # Ò LATIN CAPITAL LETTER O WITH GRAVE
00D3 # Ó LATIN CAPITAL LETTER O WITH ACUTE
00D4 # Ô LATIN CAPITAL LETTER O WITH CIRCUMFLEX
00D5 # Õ LATIN CAPITAL LETTER O WITH TILDE
00D6 # Ö LATIN CAPITAL LETTER O WITH DIAERESIS
00D7 # × MULTIPLICATION SIGN
00D8 # Ø LATIN CAPITAL LETTER O WITH STROKE
00D9 # Ù LATIN CAPITAL LETTER U WITH GRAVE
00DA # Ú LATIN CAPITAL LETTER U WITH ACUTE
00DB # Û LATIN CAPITAL LETTER U WITH CIRCUMFLEX
00DC # Ü LATIN CAPITAL LETTER U WITH DIAERESIS
00DD # Ý LATIN CAPITAL LETTER Y WITH ACUTE
00DE # Þ LATIN CAPITAL LETTER THORN
00DF # ß LATIN SMALL LETTER SHARP S
00E0 # à LATIN SMALL LETTER A WITH GRAVE
00E1 # á LATIN SMALL LETTER A WITH ACUTE
00E2 # â LATIN SMALL LETTER A WITH CIRCUMFLEX
00E3 # ã LATIN SMALL LETTER A WITH TILDE
00E4 # ä LATIN SMALL LETTER A WITH DIAERESIS
00E5 # å LATIN SMALL LETTER A WITH RING ABOVE
00E6 # æ LATIN SMALL LETTER AE
00E7 # ç LATIN SMALL LETTER C WITH CEDILLA
00E8 # è LATIN SMALL LETTER E WITH GRAVE
00E9 # é LATIN SMALL LETTER E WITH ACUTE
00EA # ê LATIN SMALL LETTER E WITH CIRCUMFLEX
00EB # ë LATIN SMALL LETTER E WITH DIAERESIS
00EC # ì LATIN SMALL LETTER I WITH GRAVE
00ED # í LATIN SMALL LETTER I WITH ACUTE
00EE # î LATIN SMALL LETTER I WITH CIRCUMFLEX
00EF # ï LATIN SMALL LETTER I WITH DIAERESIS
00F0 # ð LATIN SMALL LETTER ETH
00F1 # ñ LATIN SMALL LETTER N WITH TILDE
00F2 # ò LATIN SMALL LETTER O WITH GRAVE
00F3 # ó LATIN SMALL LETTER O WITH ACUTE
00F4 # ô LATIN SMALL LETTER O WITH CIRCUMFLEX
00F5 # õ LATIN SMALL LETTER O WITH TILDE
00F6 # ö LATIN SMALL LETTER O WITH DIAERESIS
00F7 # ÷ DIVISION SIGN
00F8 # ø LATIN SMALL LETTER O WITH STROKE
00F9 # ù LATIN SMALL LETTER U WITH GRAVE
00FA # ú LATIN SMALL LETTER U WITH ACUTE
00FB # û LATIN SMALL LETTER U WITH CIRCUMFLEX
00FC # ü LATIN SMALL LETTER U WITH DIAERESIS
00FD # ý LATIN SMALL LETTER Y WITH ACUTE
00FE # þ LATIN SMALL LETTER THORN
00FF # ÿ LATIN SMALL LETTER Y WITH DIAERESIS
0100 # Ā LATIN CAPITAL LETTER A WITH MACRON
0101 # ā LATIN SMALL LETTER A WITH MACRON
0102 # Ă LATIN CAPITAL LETTER A WITH BREVE
0103 # ă LATIN SMALL LETTER A WITH BREVE
0104 # Ą LATIN CAPITAL LETTER A WITH OGONEK
0105 # ą LATIN SMALL LETTER A WITH OGONEK
0106 # Ć LATIN CAPITAL LETTER C WITH ACUTE
0107 # ć LATIN SMALL LETTER C WITH ACUTE
0108 # Ĉ LATIN CAPITAL LETTER C WITH CIRCUMFLEX
0109 # ĉ LATIN SMALL LETTER C WITH CIRCUMFLEX
010A # Ċ LATIN CAPITAL LETTER C WITH DOT ABOVE
010B # ċ LATIN SMALL LETTER C WITH DOT ABOVE
010C # Č LATIN CAPITAL LETTER C WITH CARON
010D # č LATIN SMALL LETTER C WITH CARON
010E # Ď LATIN CAPITAL LETTER D WITH CARON
010F # ď LATIN SMALL LETTER D WITH CARON
0110 # Đ LATIN CAPITAL LETTER D WITH STROKE
0111 # đ LATIN SMALL LETTER D WITH STROKE
0112 # Ē LATIN CAPITAL LETTER E WITH MACRON
0113 # ē LATIN SMALL LETTER E WITH MACRON
0114 # Ĕ LATIN CAPITAL LETTER E WITH BREVE
0115 # ĕ LATIN SMALL LETTER E WITH BREVE
0116 # Ė LATIN CAPITAL LETTER E WITH DOT ABOVE
0117 # ė LATIN SMALL LETTER E WITH DOT ABOVE
0118 # Ę LATIN CAPITAL LETTER E WITH OGONEK
0119 # ę LATIN SMALL LETTER E WITH OGONEK
011A # Ě LATIN CAPITAL LETTER E WITH CARON
011B # ě LATIN SMALL LETTER E WITH CARON
011C # Ĝ LATIN CAPITAL LETTER G WITH CIRCUMFLEX
011D # ĝ LATIN SMALL LETTER G WITH CIRCUMFLEX
011E # Ğ LATIN CAPITAL LETTER G WITH BREVE
011F # ğ LATIN SMALL LETTER G WITH BREVE
0120 # Ġ LATIN CAPITAL LETTER G WITH DOT ABOVE
0121 # ġ LATIN SMALL LETTER G WITH DOT ABOVE
0122 # Ģ LATIN CAPITAL LETTER G WITH CEDILLA
0123 # ģ LATIN SMALL LETTER G WITH CEDILLA
0124 # Ĥ LATIN CAPITAL LETTER H WITH CIRCUMFLEX
0125 # ĥ LATIN SMALL LETTER H WITH CIRCUMFLEX
0126 # Ħ LATIN CAPITAL LETTER H WITH STROKE
0127 # ħ LATIN SMALL LETTER H WITH STROKE
0128 # Ĩ LATIN CAPITAL LETTER I WITH TILDE
0129 # ĩ LATIN SMALL LETTER I WITH TILDE
012A # Ī LATIN CAPITAL LETTER I WITH MACRON
012B # ī LATIN SMALL LETTER I WITH MACRON
012C # Ĭ LATIN CAPITAL LETTER I WITH BREVE
012D # ĭ LATIN SMALL LETTER I WITH BREVE
012E # Į LATIN CAPITAL LETTER I WITH OGONEK
012F # į LATIN SMALL LETTER I WITH OGONEK
0130 # İ LATIN CAPITAL LETTER I WITH DOT ABOVE
0131 # ı LATIN SMALL LETTER DOTLESS I
0132 # Ĳ LATIN CAPITAL LIGATURE IJ
0133 # ĳ LATIN SMALL LIGATURE IJ
0134 # Ĵ LATIN CAPITAL LETTER J WITH CIRCUMFLEX
0135 # ĵ LATIN SMALL LETTER J WITH CIRCUMFLEX
0136 # Ķ LATIN CAPITAL LETTER K WITH CEDILLA
0137 # ķ LATIN SMALL LETTER K WITH CEDILLA
0138 # ĸ LATIN SMALL LETTER KRA
0139 # Ĺ LATIN CAPITAL LETTER L WITH ACUTE
013A # ĺ LATIN SMALL LETTER L WITH ACUTE
013B # Ļ LATIN CAPITAL LETTER L WITH CEDILLA
013C # ļ LATIN SMALL LETTER L WITH CEDILLA
013D # Ľ LATIN CAPITAL LETTER L WITH CARON
013E # ľ LATIN SMALL LETTER L WITH CARON
013F # Ŀ LATIN CAPITAL LETTER L WITH MIDDLE DOT
0140 # ŀ LATIN SMALL LETTER L WITH MIDDLE DOT
0141 # Ł LATIN CAPITAL LETTER L WITH STROKE
0142 # ł LATIN SMALL LETTER L WITH STROKE
0143 # Ń LATIN CAPITAL LETTER N WITH ACUTE
0144 # ń LATIN SMALL LETTER N WITH ACUTE
0145 # Ņ LATIN CAPITAL LETTER N WITH CEDILLA
0146 # ņ LATIN SMALL LETTER N WITH CEDILLA
0147 # Ň LATIN CAPITAL LETTER N WITH CARON
0148 # ň LATIN SMALL LETTER N WITH CARON
0149 # ŉ LATIN SMALL LETTER N PRECEDED BY APOSTROPHE
014A # Ŋ LATIN CAPITAL LETTER ENG
014B # ŋ LATIN SMALL LETTER ENG
014C # Ō LATIN CAPITAL LETTER O WITH MACRON
014D # ō LATIN SMALL LETTER O WITH MACRON
014E # Ŏ LATIN CAPITAL LETTER O WITH BREVE
014F # ŏ LATIN SMALL LETTER O WITH BREVE
0150 # Ő LATIN CAPITAL LETTER O WITH DOUBLE ACUTE
0151 # ő LATIN SMALL LETTER O WITH DOUBLE ACUTE
0152 # Œ LATIN CAPITAL LIGATURE OE
0153 # œ LATIN SMALL LIGATURE OE
0154 # Ŕ LATIN CAPITAL LETTER R WITH ACUTE
0155 # ŕ LATIN SMALL LETTER R WITH ACUTE
0156 # Ŗ LATIN CAPITAL LETTER R WITH CEDILLA
0157 # ŗ LATIN SMALL LETTER R WITH CEDILLA
0158 # Ř LATIN CAPITAL LETTER R WITH CARON
0159 # ř LATIN SMALL LETTER R WITH CARON
015A # Ś LATIN CAPITAL LETTER S WITH ACUTE
015B # ś LATIN SMALL LETTER S WITH ACUTE
015C # Ŝ LATIN CAPITAL LETTER S WITH CIRCUMFLEX
015D # ŝ LATIN SMALL LETTER S WITH CIRCUMFLEX
015E # Ş LATIN CAPITAL LETTER S WITH CEDILLA
015F # ş LATIN SMALL LETTER S WITH CEDILLA
0160 # Š LATIN CAPITAL LETTER S WITH CARON
0161 # š LATIN SMALL LETTER S WITH CARON
0162 # Ţ LATIN CAPITAL LETTER T WITH CEDILLA
0163 # ţ LATIN SMALL LETTER T WITH CEDILLA
0164 # Ť LATIN CAPITAL LETTER T WITH CARON
0165 # ť LATIN SMALL LETTER T WITH CARON
0166 # Ŧ LATIN CAPITAL LETTER T WITH STROKE
0167 # ŧ LATIN SMALL LETTER T WITH STROKE
0168 # Ũ LATIN CAPITAL LETTER U WITH TILDE
0169 # ũ LATIN SMALL LETTER U WITH TILDE
016A # Ū LATIN CAPITAL LETTER U WITH MACRON
016B # ū LATIN SMALL LETTER U WITH MACRON
016C # Ŭ LATIN CAPITAL LETTER U WITH BREVE
016D # ŭ LATIN SMALL LETTER U WITH BREVE
016E # Ů LATIN CAPITAL LETTER U WITH RING ABOVE
016F # ů LATIN SMALL LETTER U WITH RING ABOVE
0170 # Ű LATIN CAPITAL LETTER U WITH DOUBLE ACUTE
0171 # ű LATIN SMALL LETTER U WITH DOUBLE ACUTE
0172 # Ų LATIN CAPITAL LETTER U WITH OGONEK
0173 # ų LATIN SMALL LETTER U WITH OGONEK
0174 # Ŵ LATIN CAPITAL LETTER W WITH CIRCUMFLEX
0175 # ŵ LATIN SMALL LETTER W WITH CIRCUMFLEX
0176 # Ŷ LATIN CAPITAL LETTER Y WITH CIRCUMFLEX
0177 # ŷ LATIN SMALL LETTER Y WITH CIRCUMFLEX
0178 # Ÿ LATIN CAPITAL LETTER Y WITH DIAERESIS
0179 # Ź LATIN CAPITAL LETTER Z WITH ACUTE
017A # ź LATIN SMALL LETTER Z WITH ACUTE
017B # Ż LATIN CAPITAL LETTER Z WITH DOT ABOVE
017C # ż LATIN SMALL LETTER Z WITH DOT ABOVE
017D # Ž LATIN CAPITAL LETTER Z WITH CARON
017E # ž LATIN SMALL LETTER Z WITH CARON
017F # ſ LATIN SMALL LETTER LONG S
0192 # ƒ LATIN SMALL LETTER F WITH HOOK
01FA # Ǻ LATIN CAPITAL LETTER A WITH RING ABOVE AND ACUTE
01FB # ǻ LATIN SMALL LETTER A WITH RING ABOVE AND ACUTE
01FC # Ǽ LATIN CAPITAL LETTER AE WITH ACUTE
01FD # ǽ LATIN SMALL LETTER AE WITH ACUTE
01FE # Ǿ LATIN CAPITAL LETTER O WITH STROKE AND ACUTE
01FF # ǿ LATIN SMALL LETTER O WITH STROKE AND ACUTE
02C6 # ˆ MODIFIER LETTER CIRCUMFLEX ACCENT
02C7 # ˇ CARON
02C9 # ˉ MODIFIER LETTER MACRON
02D8 # ˘ BREVE
02D9 # ˙ DOT ABOVE
02DA # ˚ RING ABOVE
02DB # ˛ OGONEK
02DD # ˝ DOUBLE ACUTE ACCENT
0384 # ΄ GREEK TONOS
0385 # ΅ GREEK DIALYTIKA TONOS
0386 # Ά GREEK CAPITAL LETTER ALPHA WITH TONOS
0387 # · GREEK ANO TELEIA
0388 # Έ GREEK CAPITAL LETTER EPSILON WITH TONOS
0389 # Ή GREEK CAPITAL LETTER ETA WITH TONOS
038A # Ί GREEK CAPITAL LETTER IOTA WITH TONOS
038C # Ό GREEK CAPITAL LETTER OMICRON WITH TONOS
038E # Ύ GREEK CAPITAL LETTER UPSILON WITH TONOS
038F # Ώ GREEK CAPITAL LETTER OMEGA WITH TONOS
0390 # ΐ GREEK SMALL LETTER IOTA WITH DIALYTIKA AND TONOS
0391 # Α GREEK CAPITAL LETTER ALPHA
0392 # Β GREEK CAPITAL LETTER BETA
0393 # Γ GREEK CAPITAL LETTER GAMMA
0394 # Δ GREEK CAPITAL LETTER DELTA
0395 # Ε GREEK CAPITAL LETTER EPSILON
0396 # Ζ GREEK CAPITAL LETTER ZETA
0397 # Η GREEK CAPITAL LETTER ETA
0398 # Θ GREEK CAPITAL LETTER THETA
0399 # Ι GREEK CAPITAL LETTER IOTA
039A # Κ GREEK CAPITAL LETTER KAPPA
039B # Λ GREEK CAPITAL LETTER LAMDA
039C # Μ GREEK CAPITAL LETTER MU
039D # Ν GREEK CAPITAL LETTER NU
039E # Ξ GREEK CAPITAL LETTER XI
039F # Ο GREEK CAPITAL LETTER OMICRON
03A0 # Π GREEK CAPITAL LETTER PI
03A1 # Ρ GREEK CAPITAL LETTER RHO
03A3 # Σ GREEK CAPITAL LETTER SIGMA
03A4 # Τ GREEK CAPITAL LETTER TAU
03A5 # Υ GREEK CAPITAL LETTER UPSILON
03A6 # Φ GREEK CAPITAL LETTER PHI
03A7 # Χ GREEK CAPITAL LETTER CHI
03A8 # Ψ GREEK CAPITAL LETTER PSI
03A9 # Ω GREEK CAPITAL LETTER OMEGA
03AA # Ϊ GREEK CAPITAL LETTER IOTA WITH DIALYTIKA
03AB # Ϋ GREEK CAPITAL LETTER UPSILON WITH DIALYTIKA
03AC # ά GREEK SMALL LETTER ALPHA WITH TONOS
03AD # έ GREEK SMALL LETTER EPSILON WITH TONOS
03AE # ή GREEK SMALL LETTER ETA WITH TONOS
03AF # ί GREEK SMALL LETTER IOTA WITH TONOS
03B0 # ΰ GREEK SMALL LETTER UPSILON WITH DIALYTIKA AND TONOS
03B1 # α GREEK SMALL LETTER ALPHA
03B2 # β GREEK SMALL LETTER BETA
03B3 # γ GREEK SMALL LETTER GAMMA
03B4 # δ GREEK SMALL LETTER DELTA
03B5 # ε GREEK SMALL LETTER EPSILON
03B6 # ζ GREEK SMALL LETTER ZETA
03B7 # η GREEK SMALL LETTER ETA
03B8 # θ GREEK SMALL LETTER THETA
03B9 # ι GREEK SMALL LETTER IOTA
03BA # κ GREEK SMALL LETTER KAPPA
03BB # λ GREEK SMALL LETTER LAMDA
03BC # μ GREEK SMALL LETTER MU
03BD # ν GREEK SMALL LETTER NU
03BE # ξ GREEK SMALL LETTER XI
03BF # ο GREEK SMALL LETTER OMICRON
03C0 # π GREEK SMALL LETTER PI
03C1 # ρ GREEK SMALL LETTER RHO
03C2 # ς GREEK SMALL LETTER FINAL SIGMA
03C3 # σ GREEK SMALL LETTER SIGMA
03C4 # τ GREEK SMALL LETTER TAU
03C5 # υ GREEK SMALL LETTER UPSILON
03C6 # φ GREEK SMALL LETTER PHI
03C7 # χ GREEK SMALL LETTER CHI
03C8 # ψ GREEK SMALL LETTER PSI
03C9 # ω GREEK SMALL LETTER OMEGA
03CA # ϊ GREEK SMALL LETTER IOTA WITH DIALYTIKA
03CB # ϋ GREEK SMALL LETTER UPSILON WITH DIALYTIKA
03CC # ό GREEK SMALL LETTER OMICRON WITH TONOS
03CD # ύ GREEK SMALL LETTER UPSILON WITH TONOS
03CE # ώ GREEK SMALL LETTER OMEGA WITH TONOS
0400 # Ѐ CYRILLIC CAPITAL LETTER IE WITH GRAVE
0401 # Ё CYRILLIC CAPITAL LETTER IO
0402 # Ђ CYRILLIC CAPITAL LETTER DJE
0403 # Ѓ CYRILLIC CAPITAL LETTER GJE
0404 # Є CYRILLIC CAPITAL LETTER UKRAINIAN IE
0405 # Ѕ CYRILLIC CAPITAL LETTER DZE
0406 # І CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I
0407 # Ї CYRILLIC CAPITAL LETTER YI
0408 # Ј CYRILLIC CAPITAL LETTER JE
0409 # Љ CYRILLIC CAPITAL LETTER LJE
040A # Њ CYRILLIC CAPITAL LETTER NJE
040B # Ћ CYRILLIC CAPITAL LETTER TSHE
040C # Ќ CYRILLIC CAPITAL LETTER KJE
040D # Ѝ CYRILLIC CAPITAL LETTER I WITH GRAVE
040E # Ў CYRILLIC CAPITAL LETTER SHORT U
040F # Џ CYRILLIC CAPITAL LETTER DZHE
0410 # А CYRILLIC CAPITAL LETTER A
0411 # Б CYRILLIC CAPITAL LETTER BE
0412 # В CYRILLIC CAPITAL LETTER VE
0413 # Г CYRILLIC CAPITAL LETTER GHE
0414 # Д CYRILLIC CAPITAL LETTER DE
0415 # Е CYRILLIC CAPITAL LETTER IE
0416 # Ж CYRILLIC CAPITAL LETTER ZHE
0417 # З CYRILLIC CAPITAL LETTER ZE
0418 # И CYRILLIC CAPITAL LETTER I
0419 # Й CYRILLIC CAPITAL LETTER SHORT I
041A # К CYRILLIC CAPITAL LETTER KA
041B # Л CYRILLIC CAPITAL LETTER EL
041C # М CYRILLIC CAPITAL LETTER EM
041D # Н CYRILLIC CAPITAL LETTER EN
041E # О CYRILLIC CAPITAL LETTER O
041F # П CYRILLIC CAPITAL LETTER PE
0420 # Р CYRILLIC CAPITAL LETTER ER
0421 # С CYRILLIC CAPITAL LETTER ES
0422 # Т CYRILLIC CAPITAL LETTER TE
0423 # У CYRILLIC CAPITAL LETTER U
0424 # Ф CYRILLIC CAPITAL LETTER EF
0425 # Х CYRILLIC CAPITAL LETTER HA
0426 # Ц CYRILLIC CAPITAL LETTER TSE
0427 # Ч CYRILLIC CAPITAL LETTER CHE
0428 # Ш CYRILLIC CAPITAL LETTER SHA
0429 # Щ CYRILLIC CAPITAL LETTER SHCHA
042A # Ъ CYRILLIC CAPITAL LETTER HARD SIGN
042B # Ы CYRILLIC CAPITAL LETTER YERU
042C # Ь CYRILLIC CAPITAL LETTER SOFT SIGN
042D # Э CYRILLIC CAPITAL LETTER E
042E # Ю CYRILLIC CAPITAL LETTER YU
042F # Я CYRILLIC CAPITAL LETTER YA
0430 # а CYRILLIC SMALL LETTER A
0431 # б CYRILLIC SMALL LETTER BE
0432 # в CYRILLIC SMALL LETTER VE
0433 # г CYRILLIC SMALL LETTER GHE
0434 # д CYRILLIC SMALL LETTER DE
0435 # е CYRILLIC SMALL LETTER IE
0436 # ж CYRILLIC SMALL LETTER ZHE
0437 # з CYRILLIC SMALL LETTER ZE
0438 # и CYRILLIC SMALL LETTER I
0439 # й CYRILLIC SMALL LETTER SHORT I
043A # к CYRILLIC SMALL LETTER KA
043B # л CYRILLIC SMALL LETTER EL
043C # м CYRILLIC SMALL LETTER EM
043D # н CYRILLIC SMALL LETTER EN
043E # о CYRILLIC SMALL LETTER O
043F # п CYRILLIC SMALL LETTER PE
0440 # р CYRILLIC SMALL LETTER ER
0441 # с CYRILLIC SMALL LETTER ES
0442 # т CYRILLIC SMALL LETTER TE
0443 # у CYRILLIC SMALL LETTER U
0444 # ф CYRILLIC SMALL LETTER EF
0445 # х CYRILLIC SMALL LETTER HA
0446 # ц CYRILLIC SMALL LETTER TSE
0447 # ч CYRILLIC SMALL LETTER CHE
0448 # ш CYRILLIC SMALL LETTER SHA
0449 # щ CYRILLIC SMALL LETTER SHCHA
044A # ъ CYRILLIC SMALL LETTER HARD SIGN
044B # ы CYRILLIC SMALL LETTER YERU
044C # ь CYRILLIC SMALL LETTER SOFT SIGN
044D # э CYRILLIC SMALL LETTER E
044E # ю CYRILLIC SMALL LETTER YU
044F # я CYRILLIC SMALL LETTER YA
0450 # ѐ CYRILLIC SMALL LETTER IE WITH GRAVE
0451 # ё CYRILLIC SMALL LETTER IO
0452 # ђ CYRILLIC SMALL LETTER DJE
0453 # ѓ CYRILLIC SMALL LETTER GJE
0454 # є CYRILLIC SMALL LETTER UKRAINIAN IE
0455 # ѕ CYRILLIC SMALL LETTER DZE
0456 # і CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I
0457 # ї CYRILLIC SMALL LETTER YI
0458 # ј CYRILLIC SMALL LETTER JE
0459 # љ CYRILLIC SMALL LETTER LJE
045A # њ CYRILLIC SMALL LETTER NJE
045B # ћ CYRILLIC SMALL LETTER TSHE
045C # ќ CYRILLIC SMALL LETTER KJE
045D # ѝ CYRILLIC SMALL LETTER I WITH GRAVE
045E # ў CYRILLIC SMALL LETTER SHORT U
045F # џ CYRILLIC SMALL LETTER DZHE
0490 # Ґ CYRILLIC CAPITAL LETTER GHE WITH UPTURN
0491 # ґ CYRILLIC SMALL LETTER GHE WITH UPTURN
1E80 # Ẁ LATIN CAPITAL LETTER W WITH GRAVE
1E81 # ẁ LATIN SMALL LETTER W WITH GRAVE
1E82 # Ẃ LATIN CAPITAL LETTER W WITH ACUTE
1E83 # ẃ LATIN SMALL LETTER W WITH ACUTE
1E84 # Ẅ LATIN CAPITAL LETTER W WITH DIAERESIS
1E85 # ẅ LATIN SMALL LETTER W WITH DIAERESIS
1EF2 # Ỳ LATIN CAPITAL LETTER Y WITH GRAVE
1EF3 # ỳ LATIN SMALL LETTER Y WITH GRAVE
2013 # – EN DASH
2014 # — EM DASH
2015 # ― HORIZONTAL BAR
2017 # ‗ DOUBLE LOW LINE
2018 # ‘ LEFT SINGLE QUOTATION MARK
2019 # ’ RIGHT SINGLE QUOTATION MARK
201A # ‚ SINGLE LOW-9 QUOTATION MARK
201B # ‛ SINGLE HIGH-REVERSED-9 QUOTATION MARK
201C # “ LEFT DOUBLE QUOTATION MARK
201D # ” RIGHT DOUBLE QUOTATION MARK
201E # „ DOUBLE LOW-9 QUOTATION MARK
2020 # † DAGGER
2021 # ‡ DOUBLE DAGGER
2022 # • BULLET
2026 # … HORIZONTAL ELLIPSIS
2030 # ‰ PER MILLE SIGN
2032 # ′ PRIME
2033 # ″ DOUBLE PRIME
2039 # ‹ SINGLE LEFT-POINTING ANGLE QUOTATION MARK
203A # › SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
203C # ‼ DOUBLE EXCLAMATION MARK
203E # ‾ OVERLINE
2044 # ⁄ FRACTION SLASH
207F # ⁿ SUPERSCRIPT LATIN SMALL LETTER N
20A3 # ₣ FRENCH FRANC SIGN
20A4 # ₤ LIRA SIGN
20A7 # ₧ PESETA SIGN
20AC # € EURO SIGN
2105 # ℅ CARE OF
2113 # ℓ SCRIPT SMALL L
2116 # № NUMERO SIGN
2122 # ™ TRADE MARK SIGN
2126 # Ω OHM SIGN
212E # ℮ ESTIMATED SYMBOL
215B # ⅛ VULGAR FRACTION ONE EIGHTH
215C # ⅜ VULGAR FRACTION THREE EIGHTHS
215D # ⅝ VULGAR FRACTION FIVE EIGHTHS
215E # ⅞ VULGAR FRACTION SEVEN EIGHTHS
2190 # ← LEFTWARDS ARROW
2191 # ↑ UPWARDS ARROW
2192 # → RIGHTWARDS ARROW
2193 # ↓ DOWNWARDS ARROW
2194 # ↔ LEFT RIGHT ARROW
2195 # ↕ UP DOWN ARROW
21A8 # ↨ UP DOWN ARROW WITH BASE
2202 # ∂ PARTIAL DIFFERENTIAL
2206 # ∆ INCREMENT
220F # ∏ N-ARY PRODUCT
2211 # ∑ N-ARY SUMMATION
2212 # − MINUS SIGN
2215 # ∕ DIVISION SLASH
2219 # ∙ BULLET OPERATOR
221A # √ SQUARE ROOT
221E # ∞ INFINITY
221F # ∟ RIGHT ANGLE
2229 # ∩ INTERSECTION
222B # ∫ INTEGRAL
2248 # ≈ ALMOST EQUAL TO
2260 # ≠ NOT EQUAL TO
2261 # ≡ IDENTICAL TO
2264 # ≤ LESS-THAN OR EQUAL TO
2265 # ≥ GREATER-THAN OR EQUAL TO
2302 # ⌂ HOUSE
2310 # ⌐ REVERSED NOT SIGN
2320 # ⌠ TOP HALF INTEGRAL
2321 # ⌡ BOTTOM HALF INTEGRAL
2500 # ─ BOX DRAWINGS LIGHT HORIZONTAL
2502 # │ BOX DRAWINGS LIGHT VERTICAL
250C # ┌ BOX DRAWINGS LIGHT DOWN AND RIGHT
2510 # ┐ BOX DRAWINGS LIGHT DOWN AND LEFT
2514 # └ BOX DRAWINGS LIGHT UP AND RIGHT
2518 # ┘ BOX DRAWINGS LIGHT UP AND LEFT
251C # ├ BOX DRAWINGS LIGHT VERTICAL AND RIGHT
2524 # ┤ BOX DRAWINGS LIGHT VERTICAL AND LEFT
252C # ┬ BOX DRAWINGS LIGHT DOWN AND HORIZONTAL
2534 # ┴ BOX DRAWINGS LIGHT UP AND HORIZONTAL
253C # ┼ BOX DRAWINGS LIGHT VERTICAL AND HORIZONTAL
2550 # ═ BOX DRAWINGS DOUBLE HORIZONTAL
2551 # ║ BOX DRAWINGS DOUBLE VERTICAL
2552 # ╒ BOX DRAWINGS DOWN SINGLE AND RIGHT DOUBLE
2553 # ╓ BOX DRAWINGS DOWN DOUBLE AND RIGHT SINGLE
2554 # ╔ BOX DRAWINGS DOUBLE DOWN AND RIGHT
2555 # ╕ BOX DRAWINGS DOWN SINGLE AND LEFT DOUBLE
2556 # ╖ BOX DRAWINGS DOWN DOUBLE AND LEFT SINGLE
2557 # ╗ BOX DRAWINGS DOUBLE DOWN AND LEFT
2558 # ╘ BOX DRAWINGS UP SINGLE AND RIGHT DOUBLE
2559 # ╙ BOX DRAWINGS UP DOUBLE AND RIGHT SINGLE
255A # ╚ BOX DRAWINGS DOUBLE UP AND RIGHT
255B # ╛ BOX DRAWINGS UP SINGLE AND LEFT DOUBLE
255C # ╜ BOX DRAWINGS UP DOUBLE AND LEFT SINGLE
255D # ╝ BOX DRAWINGS DOUBLE UP AND LEFT
255E # ╞ BOX DRAWINGS VERTICAL SINGLE AND RIGHT DOUBLE
255F # ╟ BOX DRAWINGS VERTICAL DOUBLE AND RIGHT SINGLE
2560 # ╠ BOX DRAWINGS DOUBLE VERTICAL AND RIGHT
2561 # ╡ BOX DRAWINGS VERTICAL SINGLE AND LEFT DOUBLE
2562 # ╢ BOX DRAWINGS VERTICAL DOUBLE AND LEFT SINGLE
2563 # ╣ BOX DRAWINGS DOUBLE VERTICAL AND LEFT
2564 # ╤ BOX DRAWINGS DOWN SINGLE AND HORIZONTAL DOUBLE
2565 # ╥ BOX DRAWINGS DOWN DOUBLE AND HORIZONTAL SINGLE
2566 # ╦ BOX DRAWINGS DOUBLE DOWN AND HORIZONTAL
2567 # ╧ BOX DRAWINGS UP SINGLE AND HORIZONTAL DOUBLE
2568 # ╨ BOX DRAWINGS UP DOUBLE AND HORIZONTAL SINGLE
2569 # ╩ BOX DRAWINGS DOUBLE UP AND HORIZONTAL
256A # ╪ BOX DRAWINGS VERTICAL SINGLE AND HORIZONTAL DOUBLE
256B # ╫ BOX DRAWINGS VERTICAL DOUBLE AND HORIZONTAL SINGLE
256C # ╬ BOX DRAWINGS DOUBLE VERTICAL AND HORIZONTAL
2580 # ▀ UPPER HALF BLOCK
2584 # ▄ LOWER HALF BLOCK
2588 # █ FULL BLOCK
258C # ▌ LEFT HALF BLOCK
2590 # ▐ RIGHT HALF BLOCK
2591 # ░ LIGHT SHADE
2592 # ▒ MEDIUM SHADE
2593 # ▓ DARK SHADE
25A0 # ■ BLACK SQUARE
25A1 # □ WHITE SQUARE
25AA # ▪ BLACK SMALL SQUARE
25AB # ▫ WHITE SMALL SQUARE
25AC # ▬ BLACK RECTANGLE
25B2 # ▲ BLACK UP-POINTING TRIANGLE
25BA # ► BLACK RIGHT-POINTING POINTER
25BC # ▼ BLACK DOWN-POINTING TRIANGLE
25C4 # ◄ BLACK LEFT-POINTING POINTER
25CA # ◊ LOZENGE
25CB # ○ WHITE CIRCLE
25CF # ● BLACK CIRCLE
25D8 # ◘ INVERSE BULLET
25D9 # ◙ INVERSE WHITE CIRCLE
25E6 # ◦ WHITE BULLET
263A # ☺ WHITE SMILING FACE
263B # ☻ BLACK SMILING FACE
263C # ☼ WHITE SUN WITH RAYS
2640 # ♀ FEMALE SIGN
2642 # ♂ MALE SIGN
2660 # ♠ BLACK SPADE SUIT
2663 # ♣ BLACK CLUB SUIT
2665 # ♥ BLACK HEART SUIT
2666 # ♦ BLACK DIAMOND SUIT
266A # ♪ EIGHTH NOTE
266B # ♫ BEAMED EIGHTH NOTES
FB01 # ﬁ LATIN SMALL LIGATURE FI
FB02 # ﬂ LATIN SMALL LIGATURE FL"""

wgl4_set = set(int(code, 16) for code in re.findall('^[0-9A-F]{4}', wgl4_doc, re.M))

UnicodeRange = namedtuple('UnicodeRange', ['name', 'start', 'end'])
wgl4_ranges = [
    UnicodeRange("C0 Controls and Basic Latin", 0x0000, 0x007F),
    UnicodeRange("C1 Controls and Latin-1 Supplement", 0x0080, 0x00FF),
    UnicodeRange("Latin Extended-A", 0x0100, 0x017F),
    UnicodeRange("Latin Extended-B", 0x0180, 0x024F),
    UnicodeRange("Spacing Modifier Letters", 0x02B0, 0x02FF),
    UnicodeRange("Greek and Coptic", 0x0370, 0x03FF),
    UnicodeRange("Cyrillic", 0x0400, 0x04FF),
    UnicodeRange("Latin Extended Additional", 0x1E00, 0x1EFF),
    UnicodeRange("General Punctuation", 0x2000, 0x206F),
    UnicodeRange("Superscripts and Subscript", 0x2070, 0x209F),
    UnicodeRange("Currency Symbols", 0x20A0, 0x20CF),
    UnicodeRange("Letterlike Symbols", 0x2100, 0x214F),
    UnicodeRange("Number Forms", 0x2150, 0x218F),
    UnicodeRange("Arrows", 0x2190, 0x21FF),
    UnicodeRange("Mathematical Operators", 0x2200, 0x22FF),
    UnicodeRange("Miscellaneous Technical", 0x2300, 0x23FF),
    UnicodeRange("Box Drawing", 0x2500, 0x257F),
    UnicodeRange("Block Elements", 0x2580, 0x259F),
    UnicodeRange("Geometric Shapes", 0x25A0, 0x25FF),
    UnicodeRange("Miscellaneous Symbols", 0x2600, 0x26FF),
    UnicodeRange("Private Use Area", 0xF000, 0xF00F),
    UnicodeRange("Alphabet presentation form", 0xFB00, 0xFB0F),
]